version: '3.9'

services:

  db:
    image: postgres:16.3
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: students_db
      POSTGRES_USER: devapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: